name: record_video
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Stream camera
  path_provider: ^2.1.3
  media_kit: 1.1.10                             # Primary package.
  media_kit_video: 1.2.4                      # For video rendering.
  media_kit_libs_video: 1.0.4
  dropdown_button2: 2.3.9
  get: ^4.6.6
  cupertino_icons: ^1.0.6
  ionicons: ^0.2.2
  uuid: 4.4.0
  equatable: 2.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.9
  json_serializable: 6.8.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

